export default {
  port: 8000,
  dbUri: "mongodb://127.0.0.1:27017/personalNftDb",
  logLevel: "info",
  // these are the values generated by the mailer testnet
  // upon deployment a proper smtp server will be used
  smtp: {
    user: "gonjqg4dj4ehaplk@ethereal.email",
    pass: "e6DWek8B8Fn9cWSnGk",
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
  },
};
