export default {
  port: 8000,
  // dbUri: "mongodb://localhost:27017/personalNftDb",
  dbUri: process.env.ATLAS_URI,
  logLevel: "info",
  accessTokenPrivateKey: process.env.ACCESS_TOKEN_PRIVATE_KEY,
  accessTokenPublicKey: process.env.ACCESS_TOKEN_PUBLIC_KEY,
  refreshTokenPrivateKey: process.env.REFRESH_PRIVATE_KEY,
  refreshTokenPublicKey: process.env.REFRESH_PUBLIC_KEY,
  // these are the values generated by the mailer testnet
  // upon deployment a proper smtp server will be used
  smtp: {
    user: "ij4xq7giuoqz7rua@ethereal.email",
    pass: "HRGwBPVJfDCAtzzAdZ",
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
  },
};
