export default {
  port: 8000,
  dbUri: "mongodb://localhost:27017/personalNftDb",
  logLevel: "info",
  // these are the values generated by the mailer testnet
  // upon deployment a proper smtp server will be used
  smtp: {
    user: "ij4xq7giuoqz7rua@ethereal.email",
    pass: "HRGwBPVJfDCAtzzAdZ",
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
  },
};
